config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :zones do
  	resources :contents
	get "login" => "sessions#new", as: :login
	post "session" => "sessions#create", as: :session
	delete "session" => "sessions#destroy"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :zone
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contents
  
  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  helper_method :current_user
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :set_zone
  before_action :authorize

  # GET /zones/:zone_id/contents
  # GET /zones/:zone_id/contents.json
  def index
    @contents = current_user.contents.where(zone_id: @zone.id)
  end

  # GET /zones/:zone_id/contents/1
  # GET /zones/:zone_id/contents/1.json
  def show
    send_data(@content.file, filename: @content.name, disposition: :attachment)
  end

  # GET /zones/:zone_id/contents/new
  def new
    @content = Content.new
  end

  # GET /zones/:zone_id/contents/1/edit
  def edit
  end

  # POST /zones/:zone_id/contents
  # POST /zones/:zone_id/contents.json
  def create
    file = content_params[:file]
    @content = Content.new(
      name: file.original_filename,
      file: file.read,
      user_id: current_user.id,
      zone_id: @zone.id
    )

    respond_to do |format|
      if @content.save
        format.html { redirect_to zone_contents_url(@zone), notice: 'ファイルを登録しました' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/:zone_id/contents/1
  # PATCH/PUT /zones/:zone_id/contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to zone_contents_url(@zone), notice: 'ファイルを更新しました' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/:zone_id/contents/1
  # DELETE /zones/:zone_id/contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to zone_contents_url(@zone), notice: 'ファイルを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    def set_zone
      @zone = Zone.find(params[:zone_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:file)
    end

    def authorize
      unless current_user
        redirect_to :zone_login
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_zone

  #ログイン画面
  def new
    @form = LoginForm.new
    render action: "new"
  end

  # ログイン
  def create
    @form = LoginForm.new(login_form_params)
    if @form.uid.present?
      user = User.find_by(uid: @form.uid)
    end
    if Authenticator.new(user).authenticate(@form.password)
      session[:user_id] = user.id
      flash.notice = "ログインしました"
      redirect_to zone_contents_path(@zone)
    else
      flash.now.alert = "ユーザー名またはパスワードが違います"
      render action: "new"
    end
  end

  # ログアウト
  def destroy
    session.delete(:user_id)
    flash.notice = "ログアウトしました"
    redirect_to zone_login_path(@zone)
  end

  private
    def set_zone
      @zone = Zone.find(params[:zone_id])
    end

    def login_form_params
      params.require(:login_form).permit(:uid, :password)
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end

    def authorize
      unless current_user
        redirect_to :root
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_form.html.slim
= form_for [@zone,@content] do |f|
	.field
		= f.file_field :file
	.actions
		= f.submit "アップロード", class: "btn btn-primary"

app/views/contents/edit.html.slim
- model_class = Content
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contents/index.html.slim
- model_class = Content
.page-header
  h1 登録ファイル一覧

ui.nav.nav-tabs
  li.active role="presentation"
    a href="#"
      bold 保留
  li role="presentation"
    a href="#"
      | 送出
  li role="presentation"
    a href="#"
      | 削除

hr

table.table.table-striped
  thead
    tr
      th.col-xs-1 No
      th.col-xs-5 ファイル名
      th.col-xs-2 参照許可
      th.col-xs-2 登録ユーザー
      th.col-xs-2 =t '.actions', :default => t("helpers.actions")
  tbody
    - @contents.each do |content|
      tr
        td= link_to content.id, zone_content_path(@zone,content)
        td= content.name
        td= content.zone&.name
        td= content.user&.name
        td
          = link_to t('.show', :default => t("helpers.links.show")), zone_content_path(@zone,content),  :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_zone_content_path(@zone,content), :class => 'btn btn-default btn-xs'
          '
          = link_to "削除", zone_content_path(@zone,content), method: :delete, data: { confirm: "本当に削除しますか？" }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_zone_content_path(@zone), :class => 'btn btn-primary'

app/views/contents/new.html.slim
- model_class = Content
.page-header
  h1 ファイル登録
= render :partial => "form"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Fg"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"FileGuard
          .navbar-collapse.collapse.navbar-responsive-collapse
            - if @zone
              ul.nav.navbar-nav
                = menu_item @zone.name
            ul.nav.navbar-nav.pull-right
              - if current_user
                = drop_down current_user.name
                  li= link_to "logout", :zone_session, method: :delete
              - else
                li= link_to "login", :zone_login

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield


      footer
        p &copy; Company 2018

app/views/top/index.html.slim
h1 Top#index
p Find me in app/views/top/index.html.slim

app/views/users/_form.html.slim
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :uid, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :uid, :class => 'form-control'
    = f.error_span(:uid)
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :hashed_password, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :hashed_password, :class => 'form-control'
    = f.error_span(:hashed_password)
  .form-group
    = f.label :start_date, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :start_date, :class => 'form-control'
    = f.error_span(:start_date)
  .form-group
    = f.label :end_date, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :end_date, :class => 'form-control'
    = f.error_span(:end_date)
  .form-group
    = f.label :suspended, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :suspended, :class => 'form-control'
    = f.error_span(:suspended)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:uid)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:start_date)
      th= model_class.human_attribute_name(:end_date)
      th= model_class.human_attribute_name(:suspended)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @users.each do |user|
      tr
        td= link_to user.id, user_path(user)
        td= user.uid
        td= user.name
        td= user.start_date
        td= user.end_date
        td= user.suspended
        td=l user.created_at
        td
          = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:uid) + ':'
  br
  = @user.uid
p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @user.name
p
  strong= model_class.human_attribute_name(:hashed_password) + ':'
  br
  = @user.hashed_password
p
  strong= model_class.human_attribute_name(:start_date) + ':'
  br
  = @user.start_date
p
  strong= model_class.human_attribute_name(:end_date) + ':'
  br
  = @user.end_date
p
  strong= model_class.human_attribute_name(:suspended) + ':'
  br
  = @user.suspended

= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'